run:
  skip-dirs:
    - proto/gen # Generated package. We can ignore
  allow-parallel-runners: true
  go: "1.21"
# golangci-lint by default ignores some staticcheck and vet raised issues that
# are actually important to catch. The following ensures that we do not ignore
# those tools ever.
issues:
  exclude-rules:
    - linters:
        - goconst
      text: "string `UNSPECIFIED` has"
      path: redpanda/utils/utils.go
    - linters:
        - goconst
      text: "string `ANY` has"
      path: redpanda/utils/utils.go
    - linters:
        - goconst
      text: "string `UNKNOWN` has"
      path: redpanda/utils/utils.go

  exclude-use-default: false
  max-same-issues: 0 # 0 is unlimited
  exclude:
    - Deferring unsafe method "Close" on type "io\.ReadCloser"
linters:
  disable-all: true
  enable:
    # https://golangci-lint.run/usage/linters/#enabled-by-default
    # Enabled by default linters: we want all, except errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    # Not enabled by default: we want a good chunk
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - containedctx
    - contextcheck
    - cyclop
    - decorder
    - dupword
    - durationcheck
    - errname
    - errorlint
    - exhaustive
    - exportloopref
    - gci
    - gocheckcompilerdirectives
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - gofumpt
    - goimports
    - goprintffuncname
    - gosec
    - mirror
    - misspell
    - nakedret
    - nilerr
    - noctx
    - nolintlint
    - revive
    - rowserrcheck
    - sqlclosecheck
    - stylecheck
    - tenv
    - typecheck
    - unconvert
    - wastedassign
    - whitespace
linters-settings:
  # A default case ensures we have checked everything. We should not require
  # every enum to be checked if we want to default.
  exhaustive:
    default-signifies-exhaustive: true
  # If we want to opt out of a lint, we require an explanation.
  nolintlint:
    allow-leading-space: true
    allow-unused: false
    require-explanation: true
    require-specific: true
  # We do not want every usage of fmt.Errorf to use %w.
  errorlint:
    errorf: false
  # If gofumpt is run outside a module, it assumes Go 1.0 rather than the
  # latest Go. We always want the latest formatting.
  #
  # https://github.com/mvdan/gofumpt/issues/137
  gofumpt:
    lang-version: "1.21"
  cyclop:
    max-complexity: 20
  gocyclo:
    min-complexity: 30
  gocognit:
    min-complexity: 30
  gci:
    no-prefix-comments: true # no leading comment; we allow inline for nolint
    sections:
      - standard # stdlib
      - default # everything not std, not within cloudv2
      - prefix(go.panda.dev/cloudv2) # non-apps (proto, pkg)
      - prefix(go.panda.dev/cloudv2/apps)
  # Gocritic is a meta linter that has very good lints, and most of the
  # experimental ones are very good too. There are only a few we want to opt
  # out of specifically.
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    disabled-checks:
      - evalOrder
      - importShadow
      # disabled due to 1.18 failures
      - hugeParam
      - rangeValCopy
      - typeDefFirst
      - paramTypeCombine
  # Revive is yet another metalinter with a bunch of useful lints. The below
  # opts in to all the ones we would like to use.
  revive:
    ignore-generated-header: true
    enable-all-rules: true
    severity: warning
    confidence: 0.7
    error-code: 1
    warning-code: 1
    rules:
      - name: add-constant
        disabled: true
      - name: argument-limit
        disabled: true
      - name: banned-characters
        disabled: true
      - name: cognitive-complexity
        disabled: true
      - name: confusing-naming
        disabled: true
      - name: cyclomatic
        disabled: true
      - name: file-header
        disabled: true
      - name: flag-parameter
        disabled: true
      - name: function-result-limit
        disabled: true
      - name: function-length
        disabled: true
      - name: import-shadowing
        disabled: true
      - name: line-length-limit
        disabled: true
      - name: max-public-structs
        disabled: true
      - name: modifies-parameter
        disabled: true
      - name: nested-structs
        disabled: true
      - name: package-comments # https://github.com/mgechev/revive/issues/740; stylecheck's ST1000 is better
        disabled: true
      - name: redefines-builtin-id
        disabled: true
      - name: unhandled-error
        disabled: true
      - name: var-naming
        disabled: true
      - name: comment-spacings
        disabled: true
